### ISSUE TITLE
Multiple waitlists can't be distinguished from each other. No headlines with names shown.

### ISSUE THREAD

**Issue by tylkomat** [emeneo/moodle-enrol_waitlist#11]
When using different waitlists on the same course they can't be distinguished from each other. There is no headline shown with the custom name I configured.

![grafik](https://user-images.githubusercontent.com/815915/157828428-84ae9002-8bf8-4e42-abe3-6aacb1366602.png)
![grafik](https://user-images.githubusercontent.com/815915/157828572-2803917a-b01e-477c-8c02-b91482c9bead.png)

I was about to create a pull request, but then I saw the video from @georgiachr in the other issue #9 where those headlines exist.

Is there another version which is not here or on the moodle plugins page?

**Comment by Flottertotte** [comment]
Hi @tylkomat, 

there is alreaday a [pull request](https://github.com/emeneo/moodle-enrol_waitlist/pull/10#issue-1164960002) by @georgia. It is under review. Does your PR look similar? Any feedback welcome!

Best,
Flotter

**Comment by tylkomat** [comment]
No I'm only interested name to be shown, we are not using enrolment keys. I just noticed that the name is only shown when enrolment keys are used.
![grafik](https://user-images.githubusercontent.com/815915/157848209-e0869f82-1dfe-46e4-a363-1bebe909b1d1.png)
The top waitinglist shows "Warteliste A 1.1" (now configured with enrolment key enabled). The bottom list doesn't show the expected name "Warteliste A 1.2".

**Comment by Flottertotte** [comment]
Thank you.. under review and we will merge asap!

**Comment by tylkomat** [comment]
Thank you for merging it so fast. When are you planning a release? The university doesn't want to install updates which have not been officially released.

**Comment by Flottertotte** [comment]
Sure, understand - just published new version on moodle.org
