### ISSUE TITLE
userid must be covered with metadata provider for GDPR compliance

### ISSUE THREAD

**Issue by ewallah** [emeneo/moodle-enrol_waitlist#4]
The following tables with user fields must be covered with metadata providers: user_enrol_waitlist (userid)

To check: 

- php admin/tool/phpunit/cli/init.php
- vendor/bin/phpunit "provider_testcase" privacy/tests/provider_test.php

**Comment by Flottertotte** [comment]
Hey, Thanks for pointing that out! It is fixed now? Any feedback welcome!
