### ISSUE TITLE
Wrong table

### ISSUE THREAD

**Issue by ewallah** [emeneo/moodle-enrol_waitlist#7]
The static function get_contexts_for_userid (file classes/privacy/provider.php) refers to a table called enrol_waitlist 
`FROM {enrol_waitlist} ew`
This table does not exist, so the table should refer to the correct table user_enrol_waitlist
`FROM {user_enrol_waitlist} ew`

To check: 
`vendor/bin/phpunit "tool_dataprivacy_api_testcase" admin/tool/dataprivacy/tests/api_test.php`

**Comment by Flottertotte** [comment]
We have fixed it, do you want to give it a try?

**Comment by ewallah** [comment]
THX
