### ISSUE TITLE
Compatibility issue w/ Moodle 3.10

### ISSUE THREAD

**Issue by pete1854** [emeneo/moodle-enrol_waitlist#8]
Hi,

When using this plugin on a 3.10 system we get the following error:

![Skärmbild 2021-04-14 094021](https://user-images.githubusercontent.com/47314226/114672593-98452e00-9d05-11eb-8242-712f90ebb2d8.png)

The above translated into english is: "This is a coding error that has to be fixed by a developer: add_to_log() has been removed, please rewrite your code to the new events API."

Steps to reproduce:
1. Enrol yourself to a course via the Waitlist enrolment method
2. Unenrol yourself from the course
3. Confirm that you want to unenrol yourself
4. The error is shown

Kind regards,
Peter

**Comment by Flottertotte** [comment]
We removed old log fct earlier already but missed this one. Can you please check the update works for you? Thank you!
