### ISSUE TITLE
Form id is the same for multiple instances

### ISSUE THREAD

**Issue by georgiachr** [emeneo/moodle-enrol_waitlist#9]
If I create two or more instances of this plugin, by clicking one of the "Click to enter text" field, all of them are enabled and clicked. Their form has the same element id.

**Comment by Flottertotte** [comment]
Could you please send a screenshot of where you click and what the result is? Thank you!

**Comment by georgiachr** [comment]
Dear all,

Please watch the video
https://www.loom.com/share/90457a7d89f44086ae3cf41815daea3b

I have fixed this bug, I can pull a request and apply changes if you agree.

Kind regards,

*Georgia Christodoulou*

**Comment by Flottertotte** [comment]
@georgiachr , Hello,
Got it... yes, it would be great if you send a pull request!
Thank you!
Flotter

**Comment by Flottertotte** [comment]
Merged, thank you!
